a: 20
b: -17
Vz0: 1.5
alpha: 0.7

# --- Search (lawnmower) parameters ---
search:
  enabled: true
  center_local: [0.0, 0.0]
  width: 40.0
  height: 40.0
  track_spacing: 5.0
  speed: 2.0
  z_search: 8.0
  reacquire_timeout: 2.0
